name: Vostok Android CI

on:
  pull_request:

jobs:
  checkout:
    uses: alediazper/shared-workflows/.github/workflows/android-checkout.yml@main
  build:
    uses: alediazper/shared-workflows/.github/workflows/android-build.yml@main
